.changeset/stupid-chairs-thank.md, packages/create-sheriff-config/src/utils/autoInstallPackages.ts, packages/create-sheriff-config/src/utils/getRequiredPackages.ts, packages/sheriff-constants/src/index.ts
=> ConfigError: Config (unnamed): Unexpected key "default" found.

.changeset/neat-owls-buy.md, packages/create-sheriff-config/package.json, packages/create-sheriff-config/src/utils/createFile.ts, packages/eslint-config-sheriff/package.json, pnpm-lock.yaml, turbo.json
=> fix(deps): moved @sherifforg/constants to devDeps. Fixes #150

.changeset/cyan-mugs-yell.md, apps/docs-website/docs/eslint-plugins.md, apps/docs-website/docs/features.md, apps/sheriff-webservices/package.json, apps/sheriff-webservices/src/getAllRules.ts, apps/sheriff-webservices/src/handledModules.d.ts, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getBaseConfig.ts, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/eslint-config-sheriff/src/handpickedRules/fpHandPickedRules.ts, packages/eslint-config-sheriff/src/handpickedRules/getBaseEslintHandPickedRules.ts, packages/sheriff-constants/src/index.ts, pnpm-lock.yaml
=> feat(config): removed `eslint-plugin-fp`

.changeset/sweet-bulldogs-unite.md, apps/sheriff-webservices/package.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getBaseConfig.ts, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/eslint-config-sheriff/src/handpickedRules/unicornHandPickedRules.ts, pnpm-lock.yaml
=> feat(deps): updated eslint-plugin-unicorn to latest

.changeset/loud-dryers-boil.md, .changeset/violet-eyes-cover.md, apps/config-validation-playground/src/samples/basic.ts, apps/sheriff-webservices/package.json, apps/sheriff-webservices/src/getAllRules.ts, package.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/eslint-config-sheriff/src/handpickedRules/jsdocHandPickedRules.ts, pnpm-lock.yaml
=> feat(deps): Update  eslint-plugin-jsdoc to latest

.changeset/thirty-timers-allow.md, apps/sheriff-webservices/package.json, apps/sheriff-webservices/src/getAllRules.ts, packages/eslint-config-sheriff/package.json, pnpm-lock.yaml
=> feat(deps): update `eslint-plugin-sonarjs` to latest

.changeset/bright-waves-jog.md, apps/sheriff-webservices/package.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getExportableConfig.ts, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/eslint-config-sheriff/src/handpickedRules/playwrightHandPickedRules.ts, packages/eslint-config-sheriff/src/playwrightConfig.ts, pnpm-lock.yaml
=> feat(deps): update `eslint-plugin-playwright` to latest

.changeset/two-pigs-wash.md, apps/sheriff-webservices/.typesyncrc.json, apps/sheriff-webservices/package.json, packages/eslint-config-sheriff/.typesyncrc.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getBaseConfig.ts, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/eslint-config-sheriff/src/handpickedRules/typescriptHandPickedRules.ts, pnpm-lock.yaml
=> feat(deps): update `@typescript-eslint/eslint-plugin` to latest

.changeset/funny-cars-smell.md, apps/sheriff-webservices/package.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getExportableConfig.ts, packages/eslint-config-sheriff/src/getJestConfig.ts, pnpm-lock.yaml
=> feat(deps): update `eslint-plugin-jest` to latest

.changeset/wild-peas-invite.md, apps/config-validation-playground/package.json, apps/docs-website/docs/eslint-plugins.md, apps/docs-website/docs/requirements/hard-requirements.md, apps/docs-website/package.json, apps/sheriff-webservices/package.json, apps/sheriff-webservices/src/getAllRules.ts, package.json, packages/create-sheriff-config/package.json, packages/create-sheriff-config/src/utils/autoInstallPackages.ts, packages/create-sheriff-config/src/utils/getRequiredPackages.ts, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getBaseConfig.ts, packages/eslint-config-sheriff/src/getJestConfig.ts, packages/eslint-config-sheriff/src/getVitestConfig.ts, packages/eslint-config-sheriff/src/nextjsConfig.ts, packages/sheriff-constants/src/index.ts, packages/sheriff-utils/package.json, pnpm-lock.yaml
=> Added ESLint v9 support

.changeset/four-shrimps-mate.md, packages/eslint-config-sheriff/src/handpickedRules/getBaseEslintHandPickedRules.ts, packages/eslint-config-sheriff/src/handpickedRules/typescriptHandPickedRules.ts
=> feat(config): added `no-useless-assignment` rule

.changeset/little-falcons-lick.md, packages/create-sheriff-config/src/utils/getRequiredPackages.ts
Bug was introduced in this commit: https://github.com/AndreaPontrandolfo/sheriff/commit/0a9e1f44180fa2a318481f66e195cfeed40da13a
=> Fix `getRequiredPackages` for ts-patch

.github/workflows/merge-checks.yml, .github/workflows/release.yml
=> chore(ci): node version taken from package.json is now respected

.changeset/chilled-readers-arrive.md, packages/eslint-config-sheriff/src/getReactConfig.ts
=> fix(config): implemented @eslint-react/eslint-plugin manually

.changeset/purple-terms-chew.md, apps/cli-playground/package.json, apps/config-validation-playground/package.json, apps/docs-website/package.json, apps/sheriff-webservices/package.json
=> removed versions from non publishable packages

apps/docs-website/docs/setup/manual-setup.mdx, package.json, packages/eslint-config-sheriff/src/index.ts, packages/sheriff-constants/package.json, packages/sheriff-types/package.json, pnpm-lock.yaml
=> feature(internals): fixes changesets

apps/cli-playground/tsconfig.json, apps/config-validation-playground/tsconfig.json, apps/docs-website/package.json, apps/sheriff-webservices/tsconfig.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/tsconfig.json, packages/sheriff-cli/package.json, packages/sheriff-cli/tsconfig.json, packages/sheriff-create-config/package.json, packages/sheriff-create-config/tsconfig.json, packages/sheriff-types/package.json, packages/sheriff-types/tsconfig.json, packages/sheriff-utils/package.json, packages/tsconfig/base.json
=> feat(internals): Use configDir in in reusable config

.changeset/nice-walls-cheat.md, apps/config-validation-playground/src/mocks/InfoButton.tsx, apps/config-validation-playground/src/samples/react.tsx, packages/eslint-config-sheriff/src/nextjsConfig.ts
=> feature(rules): changed some rules for nextjs

apps/config-validation-playground/package.json, apps/docs-website/docs/performance-considerations.mdx, apps/docs-website/package.json, apps/sheriff-webservices/package.json, packages/sheriff-cli/package.json, packages/sheriff-create-config/package.json, turbo.json
=> Update caching docs

apps/docs-website/docs/prior-art.mdx, apps/docs-website/docs/vscode-support.md, apps/docs-website/src/components/ComparisonTable.tsx
=> docs(website): Docs assorted fixes

.changeset/rude-fans-share.md, apps/docs-website/package.json, apps/sheriff-webservices/package.json, package.json, packages/eslint-config-sheriff/package.json, packages/sheriff-cli/package.json, packages/sheriff-constants/package.json, packages/sheriff-create-config/package.json, packages/sheriff-types/package.json
=> feat: updated "engines" field

CODE_OF_CONDUCT.md, README.md
=> chore(internals): Add CODE_OF_CONDUCT

.github/ISSUE_TEMPLATE/feature.yml, CONTRIBUTING.md, apps/docs-website/docs/prior-art.mdx, apps/sheriff-webservices/src/generateRulesDataset.ts, apps/sheriff-webservices/src/getAllRules.ts, package.json, packages/eslint-config-sheriff/package.json, packages/sheriff-types/src/index.ts, pnpm-lock.yaml
=> refactoring: removed redundant types

.changeset/cyan-owls-film.md, packages/eslint-config-sheriff/src/getBaseConfig.ts
=> feat(config): added constraints to globs of config object

apps/docs-website/docs/troubleshooting.md
=> docs(website): document `next lint` compatibility

.changeset/cyan-impalas-refuse.md, apps/config-validation-playground/eslint.config.js, apps/docs-website/docs/configuration.mdx, apps/docs-website/docs/migration-guide.mdx, apps/docs-website/docs/performance-considerations.mdx, apps/docs-website/docs/setup/manual-setup.mdx, apps/docs-website/docs/techs.md, apps/docs-website/docs/usage-in-ci.md, apps/docs-website/src/components/ConfigCombinationForm.tsx, apps/sheriff-webservices/package.json, apps/sheriff-webservices/src/getAllRules.ts, apps/sheriff-webservices/src/handledModules.d.ts, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getBaseConfig.ts, packages/eslint-config-sheriff/src/getExportableConfig.ts, packages/eslint-config-sheriff/src/getReactConfig.ts, packages/eslint-config-sheriff/src/getStorybookConfig.ts, packages/eslint-config-sheriff/src/handledModules.d.ts, packages/sheriff-cli/package.json, packages/sheriff-constants/src/index.ts, packages/sheriff-create-config/src/utils/setSheriffConfig.ts, packages/sheriff-types/src/index.ts, pnpm-lock.yaml
=> feat(config): Move Storybook support behind an option

.changeset/cyan-dragons-develop.md, .cursor/rules/avoid-inline-types-on-variables.mdc, .cursor/rules/avoid-type-assertions.mdc, .cursor/rules/no-abbreviations.mdc, README.md, apps/config-validation-playground/package.json, apps/docs-website/docs/typescript-support/tsconfig-guidelines.mdx, apps/docs-website/docs/usage-in-ci.md, apps/docs-website/package.json, apps/docs-website/sidebars.ts, apps/docs-website/src/pages/index.tsx, apps/sheriff-webservices/package.json, apps/sheriff-webservices/tsconfig.json, packages/eslint-config-sheriff/package.json, packages/eslint-config-sheriff/src/getExportableConfig.ts, packages/eslint-config-sheriff/src/index.ts, packages/sheriff-cli/eslint.config.js, packages/sheriff-cli/package.json, packages/sheriff-cli/src/index.ts, packages/sheriff-cli/src/utils/isPluginValid.ts, packages/sheriff-constants/package.json, packages/sheriff-create-config/package.json, packages/sheriff-types/package.json, packages/sheriff-utils/package.json, packages/tsconfig/base.json, pnpm-lock.yaml
=> Update TS and other fixes

apps/docs-website/package.json, apps/docs-website/src/app/blog/[slug]/page.tsx, apps/docs-website/src/app/docs/[[...slug]]/page.tsx, apps/docs-website/src/app/layout.tsx, apps/docs-website/src/lib/getLastUpdate.ts, pnpm-lock.yaml
Fix Fix last page edit #403
Closes #403
=> feat(docs): Add @vercel/analytics and @vercel/speed-insights; update getLastUpdate function to accept content type
